plugin:
  env:
    - name: LOVELY_HELM_MERGE
      value: |-
        hajimari:
          image:
            tag: v0.2.0
          hajimari:
            name: test

# helm:
#   parameters:
#     - name: image.tag
#       value: v0.2.0
#       forcestring: true
