loki-stack:
  loki:
    fullnameOverride: loki
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 20Gi
    serviceMonitor:
      enabled: true
    isDefault: false
  promtail:
    fullnameOverride: promtail
    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
