loki-stack:
  loki:
    fullnameOverride: loki
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
    serviceMonitor:
      enabled: true
    isDefault: false
  promtail:
    fullnameOverride: promtail
    serviceMonitor:
      enabled: true
    loki:
      serviceName: loki
    pipelineStages:
      - cri: {}
