apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.6.1
    chart: loki-stack
    helm:
      values: |
        fullnameOverride: loki-stack
        loki:
          fullnameOverride: loki
          serviceMonitor:
            enabled: true
        promtail:
          fullnameOverride: promtail
          serviceMonitor:
            enabled: true
          loki:
            serviceName: loki
          pipelineStages:
            - cri: {}
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
