---
- name: argocd - root app - secret
  k8s:
    definition: "{{ lookup('template', 'argocd_root_app_secret.yml.j2') | from_yaml }}"
    state: "{{ argocd_state }}"
  no_log: true

- name: argocd - root app - check main repo
  uri:
    url: "{{ argocd_root_app_repo_url }}"
    timeout: 10
  register: argocd_root_app_check_main_repo
  ignore_errors: true

- name: argocd - root app - set mirror repo as helm value
  set_fact:
    argocd_root_app_set_repo: --set repo={{ argocd_root_app_repo_mirror_url }}
  when: argocd_root_app_check_main_repo.status != 200

- name: argocd - root app - helm template
  command: >
    helm template
      root
      --include-crds
      --namespace argocd
      {{ argocd_root_app_set_repo | default('', true) }}
      ../cluster/bootstrap/root
  register: argocd_root_app_template_result
  changed_when: false

- name: argocd - root app - apply helm template
  k8s:
    namespace: argocd
    definition: "{{ argocd_root_app_template_result.stdout }}"
    state: "{{ argocd_state }}"

- name: argocd - root app - wait for applicationsets
  command: >
    kubectl -n argocd wait --timeout=300s --for condition=ResourcesUpToDate
      applicationset/system
      applicationset/platform
      applicationset/apps
  register: argocd_root_app_wait_result
  changed_when: false
  when: argocd_state == "present"
