---
vault_namespace: vault
vault_pod: vault-0
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
vault_token_k8s_secret:
  name: vault-root-token
  key: vaultData

vault_secrets:
  - path: secret/argocd
    kv: grafana-api-key={{ lookup('env', 'ARGOCD_GRAFANA_API_KEY') }}
  - path: secret/cert-manager
    kv: selectel-api-key={{ lookup('env', 'SELECTEL_API_KEY') }}
  - path: secret/common/smtp
    kv: "host={{ lookup('env', 'SMTP_HOST') }}
      port={{ lookup('env', 'SMTP_PORT') }}
      username={{ lookup('env', 'SMTP_USERNAME') }}
      password={{ lookup('env', 'SMTP_PASSWORD') }}"
  - path: secret/common/telegram
    kv: "bot-token={{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}
      chat-id={{ lookup('env', 'TELEGRAM_CHAT_ID') }}"
  - path: secret/common/ldap
    kv: "host={{ lookup('env', 'LDAP_HOST') }}
      port={{ lookup('env', 'LDAP_PORT') }}
      base-dn={{ lookup('env', 'LDAP_BASE_DN') }}
      users-dn={{ lookup('env', 'LDAP_USERS_DN') }}
      groups-dn={{ lookup('env', 'LDAP_GROUPS_DN') }}"
  - path: secret/kured
    kv: notify-url={{ lookup('env', 'KURED_NOTIFY_URL') }}
  - path: secret/kps/alertmanager
    kv: healthchecks-url={{ lookup('env', 'ALERTMANAGER_HEALTHCHECKS_URL') }}
  - path: secret/kps/grafana
    kv: "admin-user={{ lookup('env', 'GRAFANA_ADMIN_USER') }}
      admin-password={{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}
      ldap-bind-dn={{ lookup('env', 'GRAFANA_LDAP_BIND_DN') }}
      ldap-bind-password={{ lookup('env', 'GRAFANA_LDAP_BIND_PASSWORD') }}"
  - path: secret/authentik
    kv: "ak-admin-password={{ lookup('env', 'AUTHENTIK_AK_ADMIN_PASS') }}
      ak-admin-token={{ lookup('env', 'AUTHENTIK_AK_ADMIN_TOKEN') }}
      secret-key={{ lookup('env', 'AUTHENTIK_SECRET_KEY') }}
      postgresql-postgres-password={{ lookup('env', 'AUTHENTIK_POSTGRESQL_POSTGRES_PASSWORD') }}
      postgresql-password={{ lookup('env', 'AUTHENTIK_POSTGRESQL_PASSWORD') }}"
  - path: secret/ingress-nginx
    kv: maxmind-license-key={{ lookup('env', 'INGRESS_NGINX_MAXMIND_LICENSE_KEY') }}
  - path: secret/renovate
    kv: "gitea-token={{ lookup('env', 'RENOVATE_GITEA_TOKEN') }}
      github-token={{ lookup('env', 'RENOVATE_GITHUB_TOKEN') }}
      git-private-key={{ lookup('env', 'RENOVATE_GIT_PRIVATE_KEY') }}"
  - path: secret/k8s-registry-auth
    kv: dockerconfigjson={{ lookup('env', 'K8S_REGISTRY_AUTH') }}
  - path: secret/samgrabby
    kv: django-secret-key={{ lookup('env', 'SAMGRABBY_DJANGO_SECRET_KEY') }}
  - path: secret/gia
    kv: "django-secret-key={{ lookup('env', 'GIA_DJANGO_SECRET_KEY') }}
      postgres-password={{ lookup('env', 'GIA_POSTGRES_PASSWORD') }}
      postgres-user-password={{ lookup('env', 'GIA_POSTGRES_USER_PASSWORD') }}
      pgbackrest-s3-key={{ lookup('env', 'GIA_PGBACKREST_S3_KEY') }}
      pgbackrest-s3-key-secret={{ lookup('env', 'GIA_PGBACKREST_S3_SECRET') }}
      pgbackrest-s3-endpoint={{ lookup('env', 'GIA_PGBACKREST_S3_ENDPOINT') }}
      pgbackrest-s3-region={{ lookup('env', 'GIA_PGBACKREST_S3_REGION') }}
      pgbackrest-s3-bucket={{ lookup('env', 'GIA_PGBACKREST_S3_BUCKET') }}"
