---
vault_namespace: vault
vault_pod: vault-0
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
vault_token_k8s_secret:
  name: vault-root-token
  key: vaultData

vault_secrets:
  - path: secret/common
    kv: foo=bar
  - path: secret/apps/guestbook
    kv: "user=admin
      password={{ lookup('env', 'GUESTBOOK_PASSWORD') }}"
