vikunja:
  image:
    repository: caddy
    tag: 2.5.2-alpine
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host tasks.devmem.ru
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  additionalContainers:
    - name: api
      image: vikunja/api:unstable
      imagePullPolicy: Always
      volumeMounts:
        - name: files
          mountPath: /app/vikunja/files
        - name: config
          mountPath: /app/vikunja/config.yml
          subPath: config.yml
    - name: frontend
      image: vikunja/frontend:unstable
      imagePullPolicy: Always
  podSecurityContext:
    fsGroup: 1000
  persistence:
    files:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      mountpath: /app/vikunja/files
    config:
      enabled: true
      type: secret
      name: vikunja-config-secret
  postgresql:
    enabled: false
