---
- name: longhorn - download manifest
  get_url:
    url: "{{ longhorn_manifest_url }}"
    dest: "{{ longhorn_manifest_dest }}"
    mode: 0644

- name: longhorn - apply manifest
  k8s:
    src: "{{ longhorn_manifest_dest }}"
    state: "{{ longhorn_state }}"

- name: longhorn - create ingress
  k8s:
    definition: "{{ lookup('file', 'longhorn-frontend-ingress.yaml') }}"
    state: "{{ longhorn_state }}"
