apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      data:
        loki.yaml: |
          auth_enabled: false
          chunk_store_config:
            max_look_back_period: 0s
          compactor:
            shared_store: s3
            working_directory: /data/loki/boltdb-shipper-compactor
          ingester:
            chunk_block_size: 262144
            chunk_idle_period: 3m
            chunk_retain_period: 1m
            lifecycler:
              ring:
                replication_factor: 1
            max_transfer_retries: 0
            wal:
              dir: /data/loki/wal
          limits_config:
            enforce_metric_name: false
            max_entries_limit_per_query: 5000
            reject_old_samples: true
            reject_old_samples_max_age: 168h
          memberlist:
            join_members:
              - loki-memberlist
          schema_config:
            configs:
              - from: "2020-10-24"
                store: boltdb-shipper
                object_store: filesystem
                schema: v11
                index:
                  prefix: index_
                  period: 24h
              - from: "2022-07-26"
                store: boltdb-shipper
                object_store: s3
                schema: v11
                index:
                  prefix: index_
                  period: 24h
          server:
            grpc_listen_port: 9095
            http_listen_port: 3100
          storage_config:
            aws:
              endpoint: s3.home.devmem.ru
              bucketnames: loki
              access_key_id: {{ `"{{ .s3Key }}"` }}
              secret_access_key: {{ `"{{ .s3KeySecret }}"` }}
              s3forcepathstyle: true
            boltdb_shipper:
              active_index_directory: /data/loki/boltdb-shipper-active
              cache_location: /data/loki/boltdb-shipper-cache
              resync_interval: 5s
              shared_store: s3
            filesystem:
              directory: /data/loki/chunks
  data:
    - secretKey: s3Key
      remoteRef:
        key: secret/loki
        property: s3-key
    - secretKey: s3KeySecret
      remoteRef:
        key: secret/loki
        property: s3-key-secret
