---
k8s_cluster_controlplane_group: k8s_controlplane
k8s_cluster_workers_group: k8s_workers
k8s_cluster_lb_group: k8s_lb

k8s_cluster_user_home: /home/{{ ansible_user }}/.kube

k8s_cluster_kubeadm_config: /etc/kubernetes/kubeadm-config.yml
k8s_cluster_name: infra
k8s_cluster_pod_network: 10.244.0.0/16
k8s_cluster_control_plane_endpoint: 192.168.13.254

k8s_cluster_pod_network_manifest_url: https://projectcalico.docs.tigera.io/v3.22/manifests/calico.yaml
k8s_cluster_pod_network_manifest: "{{ k8s_cluster_user_home }}/calico.yaml"

k8s_cluster_lb_keepalived_interface:
  VI_01:
    state: "{{ (groups[k8s_cluster_lb_group][0] == inventory_hostname) | ternary('MASTER', 'BACKUP')}}"
    interface: "{{ ansible_default_ipv4.alias }}"
    priority: "{{ 150 if groups[k8s_cluster_lb_group][0] == inventory_hostname \
      else 150 - groups[k8s_cluster_lb_group].index(inventory_hostname) }}"
    virtual_router_id: "60"
    advert_int: "1"
    authentication:
      auth_type: PASS
      auth_pass: 10PASS01
    unicast_src_ip: "{{ ansible_host }}"
    unicast_peer: "{{ groups[k8s_cluster_lb_group] \
      | map('extract', hostvars, ['ansible_host']) \
      | list | d([]) \
      | difference([ansible_host]) }}"
    virtual_ipaddress:
      - "{{ k8s_cluster_control_plane_endpoint }}/24"
    track_script:
      - check_haproxy
