apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: {{` "{{ .giteaToken }}" `}}
        GITHUB_COM_TOKEN: {{` "{{ .githubToken }}" `}}
  data:
    - secretKey: giteaToken
      remoteRef:
        key: secret/renovate
        property: gitea-token
    - secretKey: githubToken
      remoteRef:
        key: secret/renovate
        property: github-token
