---
- name: kubernetes - install utils packages
  package:
    name: "{{ kubernetes_utils_packages }}"
    state: present

- name: kubernetes - download binaries
  get_url:
    url: "{{ item }}"
    dest: "{{ bin_dir }}"
    mode: 0755
    owner: root
    group: root
  loop: "{{ kubernetes_bins }}"
  notify: kubelet - restart

- name: kubernetes - kubelet - copy systemd service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    mode: 0644
    owner: root
    group: root
  notify: kubelet - restart

- name: kubernetes - kubelet - create service override directory
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    recurse: yes

- name: kubernetes - kubelet - copy service override
  template:
    src: 10-kubeadm.conf.j2
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    mode: 0644
    owner: root
    group: root
  notify: kubelet - restart

- name: kubernetes - flush handlers
  meta: flush_handlers

- name: kubernetes - kubelet - enable and start
  service:
    name: kubelet
    enabled: yes
    state: started

- name: kubernetes - pull images
  command: kubeadm config images pull --kubernetes-version {{ kubernetes_version }}
  register: result
  changed_when:
    - '"Pulled" in result.stdout'
    - kubernetes_version in result.stdout
