---
- name: nerdctl - download
  unarchive:
    src: "{{ nerdctl_url }}"
    dest: "{{ bin_dir }}"
    mode: 0755
    owner: root
    group: root
    remote_src: yes

- name: nerdctl - create dir
  file:
    dest: "{{ nerdctl_cfg_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: nerdctl - copy config
  template:
    src: nerdctl.toml.j2
    dest: "{{ nerdctl_cfg_dir }}/nerdctl.toml"
    mode: 0644
    owner: root
    group: root
