ingress-nginx:
  controller:
    replicaCount: 2
    use-forwarded-headers: "true"
    service:
      externalTrafficPolicy: Local
    extraArgs:
      default-ssl-certificate: cert-manager/k8s-devmem-ru-tls
      enable-ssl-passthrough: "true"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
