---
- name: system - enable modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      overlay
    mode: 0644
    owner: root
    group: root

- name: system - set sysctl entries
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/k8s.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: no
    state: present
  loop:
    - { name: net.ipv4.ip_forward, value: "1" }
    - { name: net.bridge.bridge-nf-call-iptables, value: "1" }
    - { name: net.bridge.bridge-nf-call-ip6tables, value: "1" }
    - { name: net.bridge.bridge-nf-call-arptables, value: "1" }
    - { name: fs.inotify.max_user_watches, value: "524288" }
    - { name: fs.inotify.max_user_instances, value: "8192" }
    - { name: vm.max_map_count, value: "262144" }
