apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: cert-manager-webhook-selectel-ca
    patch: |-
      - op: replace
        path: /spec/duration
        value: 43800h0m0s
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: cert-manager-webhook-selectel-webhook-tls
    patch: |-
      - op: replace
        path: /spec/duration
        value: 8760h0m0s
