cert-manager:
  installCRDs: true
  extraArgs:
    - --default-issuer-name=letsencrypt-prod
    - --default-issuer-kind=ClusterIssuer
    - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
    - --dns01-recursive-nameservers-only
cert-manager-webhook-selectel:
  fullnameOverride: cert-manager-webhook-selectel
