renovate:
  cronjob:
    schedule: "0 4 * * *"
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.devmem.ru/api/v1",
        "autodiscover": true,
        "printConfig": false,
        "dependencyDashboard": true,
        "dependencyDashboardTitle": "Renovate Dashboard",
        "pre-commit": {
          "enabled": true
        }
      }
  existingSecret: renovate
