---
- name: role tasks
  include_tasks: role.yml

- name: user tasks
  include_tasks: user.yml

- name: permission tasks
  include_tasks: permission.yml

- name: token tasks
  include_tasks: token.yml

- name: fail task
  include_tasks: fail.yml
