longhorn:
  defaultSettings:
    defaultReplicaCount: 3
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    priorityClass: system-node-critical
    replicaAutoBalance: best-effort
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 3
    reclaimPolicy: Retain
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    ingressClassName: nginx
    host: longhorn.k8s.devmem.ru
    tls: true
    tlsSecret: null
