metallb:
  existingConfigMap: metallb-config
  prometheus:
    serviceAccount: prometheus-operator
    namespace: monitoring
    podMonitor:
      enabled: true
    prometheusRule:
      enabled: true
