flaresolverr:
  image:
    repository: flaresolverr/flaresolverr
    tag: v2.2.6
  env:
    TZ: Europe/Moscow
    LOG_LEVEL: info
    LOG_HTML: "false"
    CAPTCHA_SOLVER: none
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
