apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: alertmanager-notifier
  labels:
    app: alertmanager-notifier
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-notifier
  data:
    - secretKey: TELEGRAM_TOKEN
      remoteRef:
        key: secret/common/telegram
        property: bot-token
    - secretKey: TELEGRAM_CHAT_ID
      remoteRef:
        key: secret/common/telegram
        property: chat-id
