apiVersion: v1
kind: Service
metadata:
  name: alertmanager-notifier
  labels:
    app: alertmanager-notifier
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  selector:
    app: alertmanager-notifier
  ports:
    - name: http
      protocol: TCP
      port: 8899
      targetPort: http
  type: ClusterIP
