---
roles:
  - src: spirkaa.nano
  - src: spirkaa.zsh_prezto
collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 4.7.0
  - name: kubernetes.core
    version: 2.3.0
