apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: alertmanager-config
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-config
    template:
      engineVersion: v2
      metadata:
        labels:
          app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 10 }}
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          receivers:
            - name: "null"
            - name: healthchecks.io
              webhook_configs:
                - url: {{ `{{ .healthchecksUrl }}` }}
                  send_resolved: false
            - name: telegram
              webhook_configs:
                - url: http://alertmanager-notifier:8899/alert
          route:
            group_by:
              - alertname
              - instance
              - job
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: telegram
            routes:
              - matchers:
                  - alertname = "Watchdog"
                receiver: healthchecks.io
                group_interval: 2m
                repeat_interval: 2m
              - matchers:
                  - alertname = "InfoInhibitor"
                receiver: "null"
              - matchers:
                  - severity =~ "warning|critical"
                receiver: telegram
                continue: true
  data:
    - secretKey: healthchecksUrl
      remoteRef:
        key: secret/kps/alertmanager
        property: healthchecks-url
