apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: regcred
spec:
  externalSecretName: regcred
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - devmem-ru
          - gia
          - samgrabby
          - apps
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
        metadata:
          annotations: {}
          labels: {}
        data:
          .dockerconfigjson: {{` "{{ .dockerconfigjson }}" `}}
    data:
      - secretKey: dockerconfigjson
        remoteRef:
          key: secret/k8s-registry-auth
          property: dockerconfigjson
