---
- name: metallb - create namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ metallb_namespace }}"
    state: present

- name: metallb - create configmap
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metallb_configmap.yaml.j2') | from_yaml }}"
    state: present
